[package]
name = "linked_list"
version = "0.1.0"
authors = ["Soleil Yu <shengyang998@foxmail.com>"]
edition = "2018"

[dependencies]

[profile.dev]
opt-level = 3

[profile.release]
overflow-checks = true

